// Generated by CoffeeScript 1.6.2
var debounce, escapeHtml, log;

log = function() {
  var e;

  try {
    return console.log.apply(console, arguments);
  } catch (_error) {
    e = _error;
  }
};

debounce = function(func, wait, immediate) {
  var timeout;

  timeout = '';
  return function() {
    var args, callNow, context, later, result;

    context = this;
    args = arguments;
    later = function() {
      var result;

      timeout = null;
      if (!immediate) {
        return result = func.apply(context, args);
      }
    };
    callNow = immediate && !timeout;
    clearTimeout(timeout);
    timeout = setTimeout(later, wait);
    if (callNow) {
      result = func.apply(context, args);
    }
    return result;
  };
};

escapeHtml = function(string) {
  return ('' + string).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&#x27;').replace(/\//g, '&#x2F;');
};
