// Generated by CoffeeScript 1.6.2
var Error;

Error = (function() {
  Error.prototype.errorTypes = {
    1: 'desktopClient',
    2: 'errorLoginPass',
    3: 'errorConnection'
  };

  function Error(errorEl, oktell) {
    this.el = errorEl;
  }

  Error.prototype.show = function(errorType) {
    if (!this.errorTypes[errorType]) {
      return false;
    }
    return this.el.fadeIn(200);
  };

  Error.prototype.hide = function() {
    return this.el.fadeOut(200);
  };

  return Error;

})();
