// Generated by CoffeeScript 1.6.2
var Panel;

Panel = (function() {
  function Panel(actionList, usersService) {
    var filterSetter, input, phoneButtons, phonePopup, popupInited, topchanged,
      _this = this;

    this.actionList = actionList;
    this.panelNumber = actionList.panelNumber;
    this.usersService = usersService;
    this.panelNumberHasFocus = ko.observable(false);
    ko.computed(function() {
      var filteredUsers, hasFocus, number;

      hasFocus = _this.panelNumberHasFocus();
      number = _this.panelNumber();
      filteredUsers = usersService.usersForPanel();
      if (number && hasFocus && filteredUsers.length) {
        return filteredUsers[0];
      }
    });
    filterSetter = ko.computed(function() {
      return usersService.filter(_this.panelNumber());
    });
    this.popupVisible = ko.observable(false);
    input = '';
    phonePopup = '';
    phoneButtons = '';
    topchanged = false;
    this.afterRender = function(el) {
      _this.el = $(el);
      input = _this.el.find('input.b_phone_number_input');
      phoneButtons = input.parent().find('div.i_phone_popup_button');
      return input.keyup(function(e) {
        var _ref, _ref1;

        if (e.keyCode === 13) {
          if ((_ref = usersService.usersForPanel()) != null) {
            if ((_ref1 = _ref[0]) != null) {
              _ref1.doFirstAction();
            }
          }
          actionList.panelNumber('');
          return input.blur();
        }
      });
    };
    this.showPopup = function(a, b) {
      var inpitWidth;

      if (_this.popupVisible()) {
        return;
      }
      inpitWidth = input.closest(".h_phone_number_bg").width() - 8;
      phonePopup.css('width', inpitWidth);
      phonePopup.find('.b_actions_group_list').css('visibility', 'visible');
      phonePopup.fadeIn(200);
      if (!topchanged) {
        topchanged = true;
        phonePopup.offset({
          top: phonePopup.offset().top - 33
        });
      }
      return _this.popupVisible(true);
    };
    this.hidePopup = function() {
      return _this.popupVisible(false);
    };
    $(document).on("click", function(e) {
      var element;

      element = $(e.target);
      if (element.parents(".j_phone_popup_cloned").size() === 0 && element.parents(".h_phone_number_input").size() === 0) {
        return _this.hidePopup();
      }
    });
    popupInited = false;
  }

  return Panel;

})();
