// Generated by CoffeeScript 1.6.2
var PermissionsPopup;

PermissionsPopup = (function() {
  function PermissionsPopup(popupEl, oktellVoice) {
    var _this = this;

    this.el = popupEl;
    oktellVoice.on('mediaPermissionsRequest', function() {
      return _this.show();
    });
    oktellVoice.on('mediaPermissionsAccept', function() {
      return _this.hide();
    });
    oktellVoice.on('mediaPermissionsRefuse', function() {
      oktell.endCall();
      return _this.hide();
    });
  }

  PermissionsPopup.prototype.show = function() {
    this.log('Permissions Popup show!');
    return this.el.show();
  };

  PermissionsPopup.prototype.hide = function() {
    return this.el.fadeOut(200);
  };

  return PermissionsPopup;

})();
