// Generated by CoffeeScript 1.6.2
var Popup;

Popup = (function() {
  function Popup(popupEl, oktell) {
    var _this = this;

    this.el = popupEl;
    this.absContainer = this.el.find('.b_content');
    this.abonentEl = this.absContainer.find('.b_abonent').remove();
    this.el.find('.j_abort_action').bind('click', function() {
      _this.hide();
      return oktell.endCall();
    });
    this.el.find('.j_close_action').bind('click', function() {
      return _this.hide();
    });
    this.el.find('i.o_close').bind('click', function() {
      return _this.hide();
    });
    oktell.on('ringStart', function(abonents) {
      _this.setAbonents(abonents);
      return _this.show();
    });
    oktell.on('ringStop', function() {
      return _this.hide();
    });
  }

  Popup.prototype.show = function() {
    return this.el.fadeIn(200);
  };

  Popup.prototype.hide = function() {
    return this.el.fadeOut(200);
  };

  Popup.prototype.setAbonents = function(abonents) {
    var _this = this;

    this.absContainer.empty();
    return $.each(abonents, function(i, abonent) {
      var el, name, phone;

      phone = abonent.phone.toString();
      name = abonent.name.toString() || phone;
      if (name === phone) {
        phone = '';
      }
      el = _this.abonentEl.clone();
      el.find('span:first').text(name);
      el.find('span:last').text(phone);
      return _this.absContainer.append(el);
    });
  };

  return Popup;

})();
