// Generated by CoffeeScript 1.8.0
(function() {
  module.exports = function(grunt) {
    return grunt.registerMultiTask('includecoffee', 'Replace matched string by file', function() {
      var ch, config, f, file, files, fs, i, m, pos, rAll, tabs, _i, _j, _k, _len, _len1, _len2, _ref;
      config = this.data;
      fs = require('fs');
      file = fs.readFileSync(config.target).toString();
      files = [];
      rAll = new RegExp(config.regexp.source, 'gm');
      _ref = file.match(rAll) || [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        f = _ref[_i];
        m = f.match(config.regexp);
        if (m) {
          files.push(m);
        }
      }
      for (i = _j = 0, _len1 = files.length; _j < _len1; i = ++_j) {
        f = files[i];
        files[i] = [f[0], (f[1][0] === '/' ? f[1].substr(1) : f[1])];
      }
      for (_k = 0, _len2 = files.length; _k < _len2; _k++) {
        f = files[_k];
        pos = file.indexOf(f[0]);
        pos--;
        tabs = '';
        ch = file[pos];
        while (ch === "\t") {
          tabs += ch;
          ch = file[--pos];
        }
        file = file.replace(f[0], f[0] + tabs + fs.readFileSync(f[1]).toString().replace(/(\r\n|\n)/g, "\n" + tabs) + "\r\n");
      }
      return fs.writeFileSync(config.dest, file);
    });
  };

}).call(this);
